# Generated by Django 5.0.7 on 2024-08-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('content', models.TextField()),
                ('published', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'پیشنویس'), ('published', 'منشترشده')], default='draft', max_length=10, verbose_name='وضعیت انتشار')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
