# Generated by Django 5.0.7 on 2024-08-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogtechnology', '0002_alter_post_options_post_thumbnail_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='category', to='blogtechnology.category'),
        ),
    ]
